from tkinter import *
def muda_texo():
    rotulo1["text"] += texto.get()
window = Tk()
window.title("Boas Vindas")
window.geometry("450x200+400+200")
rotulo1 = Label(window, text="Seja bem vindo!", font="Impact 20 bold", pady=10)
rotulo1.pack()
container = Frame(window, pady=1, padx=10)
container.pack()
rotulo2 = Label(container, text="Nome:", font="Impact 16", pady=10)
rotulo2.pack(side=LEFT)
texto = Entry(container, font=("Times New Roman", "16"))
texto.pack(side=RIGHT)
botao = Button(window, text="Click aqui", padx=10, pady=5, bg="black", fg="white")
botao["font"] = ("Courier New", "16", "bold")
botao["command"] = muda_texo
botao.pack()
texto.focus()
window.mainloop()